### ISSUE TITLE
Golfing to save 70 bytes

### ISSUE THREAD

**Issue by chris-morgan** [GoogleChromeLabs/wasm-feature-detect#13]
I have no interest in framing this in a way suitable for landing it; I’m just leaving it because I like golfing and saw substantial room for improvement. I leave this minified code, which is about 509 bytes gzipped, rather than about 579 bytes.

Most or all of the techniques used:

- Discard the `validate` function which is actually *counter-productive* due to gzip (which compresses identical substrings brilliantly—so it doesn’t matter that `=async()=>WebAssembly.validate(new Uint8Array([0,97,115,198,1,0,0,0,` is longer, it compresses almost out of existence after the first time.)
- Arrow functions.
- Inlining the WASM rather than using functions and binding. (This’ll be a mite harder to manage if you want the WAT files separate, but it’s readily possible.)
- Shuffling things around in the two big tests to skip unnecessary structures and make them look more like one another.

Mostly due to being more direct, this form is also easier to read, faster to execute and will take less memory in the engine.

The code, with line breaks added for convenience:
```js
export const bigInt=async()=>{try{const e=BigInt(0);return(await WebAssembly.instantiate(new Uint8Array([0,97,115,109,1,0,0,0,1,6,1,96,1,126,1,126,3,2,1,0,7,5,1,1,98,0,0,10,6,1,4,0,32,0,11]))).instance.exports.b(e)===e}catch{return!1}};
export const bulkMemory=async()=>WebAssembly.validate(new Uint8Array([0,97,115,109,1,0,0,0,1,4,1,96,0,0,3,2,1,0,5,3,1,0,1,12,1,0,10,14,1,12,0,65,0,65,0,65,0,252,10,0,0,11]));
export const exceptions=async()=>WebAssembly.validate(new Uint8Array([0,97,115,109,1,0,0,0,1,4,1,96,0,0,3,2,1,0,10,9,1,7,0,6,64,7,26,11,11]));
export const multiValue=async()=>WebAssembly.validate(new Uint8Array([0,97,115,109,1,0,0,0,1,6,1,96,0,2,127,127,3,2,1,0,10,8,1,6,0,65,0,65,0,11]));
export const mutableGlobals=async()=>WebAssembly.validate(new Uint8Array([0,97,115,109,1,0,0,0,2,8,1,1,97,1,98,3,127,1,6,6,1,127,1,65,0,11,7,5,1,1,97,3,1]));
export const referenceTypes=async()=>WebAssembly.validate(new Uint8Array([0,97,115,109,1,0,0,0,1,4,1,96,0,0,3,2,1,0,10,6,1,4,0,208,26,11]));
export const saturatedFloatToInt=async()=>WebAssembly.validate(new Uint8Array([0,97,115,109,1,0,0,0,1,4,1,96,0,0,3,2,1,0,10,12,1,10,0,67,0,0,0,0,252,0,26,11]));
export const signExtensions=async()=>WebAssembly.validate(new Uint8Array([0,97,115,109,1,0,0,0,1,4,1,96,0,0,3,2,1,0,10,8,1,6,0,65,0,192,26,11]));
export const simd=async()=>WebAssembly.validate(new Uint8Array([0,97,115,109,1,0,0,0,1,4,1,96,0,0,3,2,1,0,10,9,1,7,0,65,0,253,4,26,11]));
export const tailCall=async()=>WebAssembly.validate(new Uint8Array([0,97,115,109,1,0,0,0,1,4,1,96,0,0,3,2,1,0,10,6,1,4,0,18,0,11]));
export const threads=async()=>{try{return(new MessageChannel).port1.postMessage(new SharedArrayBuffer(1)),WebAssembly.validate(new Uint8Array([0,97,115,109,1,0,0,0,1,4,1,96,0,0,3,2,1,0,5,4,1,3,1,1,10,11,1,9,0,65,0,254,16,2,0,26,11]))}catch{return!1}};
```

I also note that https://unpkg.com/wasm-feature-detect@1.2.0/dist/esm/index.js?module is not properly minified, at about a 38 byte penalty gzipped.

**Comment by surma** [comment]
Thanks for the suggestions! I implemented some of them in 8e465e06230ee6756a03d926b5366dd2a73bdc4e, which did reduce the gzip’d size by ~20 bytes. 

I didn’t golf it down to your 509, mostly because some of the optimizations require a sacrifice in readability and I don’t want to scare people away from contributing. I also don’t want to set a precedent that this is a golfing-focused project ^^ I think we are doing quite will with being around 500B :D
