### ISSUE TITLE
Memory growth test for threaded wasm

### ISSUE THREAD

**Issue by overocean** [GoogleChromeLabs/wasm-feature-detect#20]
Hi guys,

Older versions of Chrome don't allow memory growth for threaded wasm. I would like to have a test for this feature. Any advice?

Thanks,
Dan

**Comment by surma** [comment]
Interesting point. The test for this should be quite easy to write. Would you expect this to be a separate “growable memory” test or something along those lines?

**Comment by overocean** [comment]
Hi Surma,

Sorry about the late reply! Yes, it would be ideal to be a separate test.

Thanks,
Dan

**Comment by tomayac** [comment]
This sounds trivial to test via

```js
if ('grow' in WebAssembly.Memory.prototype) {
  // Supported.
}
```
