### ISSUE TITLE
render-readme.mjs swallows return code

### ISSUE THREAD

**Issue by ngzhian** [GoogleChromeLabs/wasm-feature-detect#33]
See https://github.com/GoogleChromeLabs/wasm-feature-detect/blob/master/render-readme.mjs#L41, it catches the error, logs it, but overall the script still returns 0.

When running `npm run build` which has more than a single page of output, it can be easy to miss.

**Comment by tomayac** [comment]
Getting this to work cross-platform seems impossible. For now, it seems fine to close this and remember to check the logged output carefully.
