### ISSUE TITLE
Add detector for module linking

### ISSUE THREAD

**Issue by fitzgen** [GoogleChromeLabs/wasm-feature-detect#38]
Is it possible to detect features not supported by WABT? I'd like to add a module linking detector but WABT doesn't support module linking yet.

**Comment by RReverser** [comment]
Ah that's an interesting one. What does support them? Binaryen?

**Comment by fitzgen** [comment]
https://github.com/bytecodealliance/wasm-tools and Wasmtime are the only implementations I'm aware of. I know that there were plans to implement it in lld as well, but I don't know their status.

**Comment by RReverser** [comment]
Huh. I guess it's unlikely that any JS engine will implement a feature earlier than WABT / Binaryen, so maybe it's not worth investing much time into this, but let's keep the issue open for tracking.

**Comment by 7ombie** [comment]
Is there a reason for not detecting GC? GC and Annotations are supported by WABT(JS), but not detected. I'm not sure there's anything *to detect* with Annotations, but GC seems like it should be on the list.

**Comment by RReverser** [comment]
> 
> 
> Is there a reason for not detecting GC? GC and Annotations are supported by WABT(JS), but not detected. I'm not sure there's anything _to detect_ with Annotations, but GC seems like it should be on the list.

I don't think that's related to current issue or discussion. It's best not to mix them up - please raise a separate one or, better yet, send a PR :)

**Comment by tomayac** [comment]
The [module linking proposal](https://github.com/WebAssembly/module-linking) was archived. Closing.
