### ISSUE TITLE
Can't resolve 'worker_threads' in CRA

### ISSUE THREAD

**Issue by absurdprofit** [GoogleChromeLabs/wasm-feature-detect#40]
I am trying to use OpenCV.js loader to use OpenCV in my react-app. The loader relies on wasm-feature-detect to setup the emscripten generated files (js and wasm). When I try to require("loader.js"); I get the error ```Can't resolve 'worker_threads'```. I am using typescript create react app template. Any help is greatly appreaciated.

**Comment by tomayac** [comment]
This looks like a local tooling issue indeed. The [`publint` tool is happy](https://publint.dev/wasm-feature-detect@1.5.1), too.
