### ISSUE TITLE
Exception-handling detection may need update

### ISSUE THREAD

**Issue by ajklein** [GoogleChromeLabs/wasm-feature-detect#41]
Chrome 89 & 90 now have exception-handling support enabled behind the --enable-experimental-webassembly-features flag, but turning on that flag does not check the "exception handling" box on https://webassembly.org/roadmap/ for me. I suspect wasm-feature-detect may need to be updated to match the current spec's opcodes.

**Comment by surma** [comment]
We have [a `.wat` file](https://github.com/GoogleChromeLabs/wasm-feature-detect/blob/master/src/detectors/exceptions/module.wat) that serves as the detector. I think we just need to update `wabt`, republish this package and then re-deploy webassembly.org. 

Thanks for the issue, Adam!

**Comment by surma** [comment]
Fix published in v1.2.10
