### ISSUE TITLE
memory64 not published to npm

### ISSUE THREAD

**Issue by AlphaCodeZero** [GoogleChromeLabs/wasm-feature-detect#50]
The latest version of wasm-feature-detect on npm was published 10 months ago, which doesn't include the memory64 detector.
https://www.npmjs.com/package/wasm-feature-detect

**Comment by dschuff** [comment]
Bump!
It would be nice to update https://webassembly.org/roadmap/ for memory64 but the site currently depends on the npm release of wasm-feature-detect.

**Comment by surma** [comment]
I’ll do a release once I got write access back to this repo and can merge #52

**Comment by surma** [comment]
Just published v1.3.0 containing memory64 and others
