### ISSUE TITLE
Add Wasm-GC?

### ISSUE THREAD

**Issue by kevmoo** [GoogleChromeLabs/wasm-feature-detect#60]
It'd be nice to get ahead of this...especially for some languages that are already building support

**Comment by surma** [comment]
Is there a full implementation in any engine? I know V8 is working on it, but I'm pretty sure implementation work isn't done yet.

But if you fancy helping, you can open a Draft PR and we can keep updating it as we go along.

**Comment by kevmoo** [comment]
@surma – V8 is pretty feature complete. I figured it aligned with other preview features.

I'm not bost qualified to implement things, though. 😄

**Comment by tlively** [comment]
I think the big blocker here is that WABT doesn't support WasmGC at all. @surma, is there a way to work around that? Could we use binaryen.js instead of wabt.js?

**Comment by surma** [comment]
@tlively I am not married to using wabt.js. If anyone wants to whip up a PR that replaces [`compileWat`](https://github.com/GoogleChromeLabs/wasm-feature-detect/blob/4490d7914ff5ca4a76fd1834d9154e6bb089c7ec/rollup-plugins/helpers.mjs#L20-L28) with a binaryen.js version, please feel encouraged to do so!

**Comment by surma** [comment]
Had some time to kill on a train and I was curious. I’d love some reviews on #61

**Comment by surma** [comment]
Did a little pivot. Here’s a [PR] for adding a GC detector. Code reviews welcome!

[PR]: https://github.com/GoogleChromeLabs/wasm-feature-detect/pull/62

**Comment by surma** [comment]
GC detector is publish in v1.5.0 :)
