### ISSUE TITLE
package.json missing field "main" in v1.5.1

### ISSUE THREAD

**Issue by itagn** [GoogleChromeLabs/wasm-feature-detect#65]
use wasm-feature-detect
```javascript
import { simd } from 'wasm-feature-detect';
```
then
```cmd
npm run build
```
Module not found: Error: Can't resolve 'wasm-feature-detect'

**Comment by itagn** [comment]
should be my node.js version is 12.22, not support field "exports"

**Comment by tomayac** [comment]
This looks like a local tooling issue indeed. The [`publint` tool is happy](https://publint.dev/wasm-feature-detect@1.5.1), too.
