### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by brendandahl** [GoogleChromeLabs/wasm-feature-detect#69]
It'd be nice to have these to update the roadmap.

@surma can you update?

**Comment by tomayac** [comment]
@surma Could you push a new npm release, please? There have been some recent changes.

**Comment by nikpachoo** [comment]
Hi there,
Thanks for the latest adjustments due to the GC update.
The latest version in package.json is 1.6.0, but the npm package hasn't been updated yet. 
It would be very helpful for us to get this new version.
Could you please publish it?

**Comment by tomayac** [comment]
@surma no longer works at Google. Let me ping him privately.

**Comment by tomayac** [comment]
Just released `1.6.0` to npm and am now a maintainer, apart from @surma.
