### ISSUE TITLE
simd detection ios17 

### ISSUE THREAD

**Issue by Alexufo** [GoogleChromeLabs/wasm-feature-detect#75]
When Apple announced support for simd instructions in safari with 16.4 we immediately started testing our solution, which already worked in Chrome with simd. 

We were disappointed, because calculations with simd instructions returned incorrect results. simd instructions did not work correctly and it became possible to use them only with ios17 (since this version the bug was fixed and we don't know the name of the ticket with this bug). 
In this case wasm-feature-detect detects false support for simd instructions for ios before version 17.

How to be in this case? The only option is to parse user-agent by ios version.

**Comment by tomayac** [comment]
If you have a small test case ready where a wrong result gets returned, we could change the feature detection step to first check for the presence of the feature, and then for the correctness of a calculation. To clarify the idea, the super simplified pseudocode would be something like this:

```js
if ('SIMD_plus' in Wasm) {
  // SIMD_plus is known to incorrectly return 4
  // on iOS <17. 
  const result = Wasm.SIMD_plus(1, 2);
  return result === 3;
}
return false;
```

**Comment by grateful345** [comment]
if ('SIMD_plus' in Wasm) {
  // SIMD_plus is known to incorrectly return 4
  // on iOS <17. 
  const result = Wasm.SIMD_plus(1, 2);
  return result === 3;
}
return false;

**Comment by tomayac** [comment]
Closing this since it seems like there's no further action.
