### ISSUE TITLE
Testing for Exception Handling proposal tests for old version

### ISSUE THREAD

**Issue by CryZe** [GoogleChromeLabs/wasm-feature-detect#79]
Apparently there are two versions of the exception handling proposal. The outdated version, which got shipped by all the browsers and the final versions that is still behind feature flags in the browsers ("exnref"). Currently the outdated version is being tested for.

**Comment by tomayac** [comment]
Yes, this should test for both. Are you able and willing to create a PR that would add support for both? Eventually, we can remove the outdated variant, so a PR should add a `ToDo` so it's remembered.

**Comment by tomayac** [comment]
Fixed via #81 .
