### ISSUE TITLE
Error on Firefox ESR

### ISSUE THREAD

**Issue by reynir** [GoogleChromeLabs/wasm-feature-detect#82]
I visited https://webassembly.org/features/ and was presented with the following uninformative table on Firefox 115.14.0esr:
![Screenshot from 2024-09-23 11-40-37](https://github.com/user-attachments/assets/175f39f7-1342-4b19-bd9f-8bafce09f6d1)
As you can see the table is just a list of browsers.

The web developer tools console has the following error logged:
```
Uncaught (in promise) TypeError: Object.groupBy is not a function
    <anonymous> https://webassembly.org/features.js:4
    async* https://webassembly.org/features.js:21
features.js:4:753
    <anonymous> https://webassembly.org/features.js:21
    AsyncFunctionNext self-hosted:852
    (Async: async)
    <anonymous> https://webassembly.org/features.js:21
```

Unfortunately, webassembly.org doesn't seem to list any contact method, but the page says the (broken) table is powered by this library.

**Comment by tomayac** [comment]
Oh, looks like [`Object.groupBy()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/groupBy#browser_compatibility) only works as of Firefox 119. We can either polyfill it, or implement it differently. Let me get back to this.

**Comment by tomayac** [comment]
Fixed via https://github.com/WebAssembly/website/commit/0a60e1ac0cf2129894f5a020491be952f9043727. Once this gets deployed, the code should work.

**Comment by reynir** [comment]
That was quick! Thanks
